# Build custom atac reference binning

The genome binning strategy used to build the ATAC reference MUST be the same used for the following preprocessing of the ATAC samples.

## Setting up reference from custom genome

The workflow may start from one of two staring point:
- a FASTA file index, usually ending with `.fai` suffix.
- a chromosome size `pandas.DataFrame`

Here is the formatting of the expected `.fai` file. We only require the first and the second columns of the `.fai` file, respectively the chromosome ID and the total length of the chromosome (in base pairs).

In [1]:
import pandas as pd

In [2]:
chrom_size_real_path = "/beegfs/scratch/ric.cosr/carlino.calogero/genomes/refdata-gex-GRCh38-2024-A/fasta/genome.fa.fai"

In [3]:
pd.read_table(chrom_size_real_path, header=None).head()

       0          1          2   3   4
0   chr1  248956422          8  60  61
1  chr10  133797422  253105714  60  61
2  chr11  135086622  389133104  60  61
3  chr12  133275309  526471180  60  61
4  chr13  114364328  661967755  60  61

Given the path to the `.fai` file, preprocessing can be performed as follow:

In [4]:
import spacenumbat
from spacenumbat.preprocessing import multiome_unpaired

In [5]:
minimal_chrom_size_df = multiome_unpaired.get_minimal_chrom_size_from_fasta_index(chrom_size_real_path)

In [6]:
minimal_chrom_size_df.head()

  CHROM     length
0  chr1  248956422
1  chr2  242193529
2  chr3  198295559
3  chr4  190214555
4  chr5  181538259

Once the `pd.DataFrame` with the size of each desired chromosome is built or imported, we can proceed with the binning.

You can use a custom binning of your choice and import it. If you want a custom binning with fixed bin size this can be imported or constructed with the provided function.

To build a fixed size binning of your choice, the following function can be used:

In [7]:
bin_size = 220_000
current_binning = multiome_unpaired.get_custom_gtf_binning(minimal_chrom_size_df, 
                                                           bin_size=bin_size)

In [8]:
current_binning.head()

                                  bin_id CHROM   start      end   width
chr1:0-220000              chr1:0-220000     1       0   220000  220000
chr1:220000-440000    chr1:220000-440000     1  220000   440000  220000
chr1:440000-660000    chr1:440000-660000     1  440000   660000  220000
chr1:660000-880000    chr1:660000-880000     1  660000   880000  220000
chr1:880000-1100000  chr1:880000-1100000     1  880000  1100000  220000

To import a custom binning just import it as a `pandas.DataFrame`. Here we import the genome binning used in the R implementation of `Numbat`.

In [9]:
numbat_bins_path = "/beegfs/scratch/ric.cosr/ric.cosr/InnovationLab/spatial_dataset/spatial_multiomics/numbat_bins.tsv"

In [10]:
current_binning = pd.read_table(numbat_bins_path,index_col=0)

In [11]:
current_binning.head()

                                    bin_id CHROM    start      end    width
chr1:0-1042457              chr1:0-1042457     1        0  1042457  1042457
chr1:1042457-1265484  chr1:1042457-1265484     1  1042457  1265484   223027
chr1:1265484-1519859  chr1:1265484-1519859     1  1265484  1519859   254375
chr1:1519859-1826619  chr1:1519859-1826619     1  1519859  1826619   306760
chr1:1826619-2058465  chr1:1826619-2058465     1  1826619  2058465   231846

In [24]:
genomic_regions = current_binning.bin_id.unique().tolist()

In [25]:
genomic_regions

['chr1:0-1042457',
 'chr1:1042457-1265484',
 'chr1:1265484-1519859',
 'chr1:1519859-1826619',
 'chr1:1826619-2058465',
 'chr1:2058465-2280372',
 'chr1:2280372-2491263',
 'chr1:2491263-2817807',
 'chr1:2817807-3025418',
 'chr1:3025418-3230151',
 'chr1:3230151-3437000',
 'chr1:3437000-3645603',
 'chr1:3645603-4091348',
 'chr1:4091348-4312450',
 'chr1:4312450-4522391',
 'chr1:4522391-4733807',
 'chr1:4733807-4949751',
 'chr1:4949751-5167781',
 'chr1:5167781-5378577',
 'chr1:5378577-5586352',
 'chr1:5586352-5802602',
 'chr1:5802602-6013527',
 'chr1:6013527-6232553',
 'chr1:6232553-6468662',
 'chr1:6468662-6699855',
 'chr1:6699855-6922979',
 'chr1:6922979-7134271',
 'chr1:7134271-7347565',
 'chr1:7347565-7562625',
 'chr1:7562625-7781202',
 'chr1:7781202-8012370',
 'chr1:8012370-8246678',
 'chr1:8246678-8471404',
 'chr1:8471404-8698958',
 'chr1:8698958-8937804',
 'chr1:8937804-9174404',
 'chr1:9174404-9392992',
 'chr1:9392992-9634910',
 'chr1:9634910-9874006',
 'chr1:9874006-10127844',
 'chr1:10127844-10365738',
 'chr1:10365738-10601471',
 'chr1:10601471-10808784',
 'chr1:10808784-11040607',
 'chr1:11040607-11278872',
 'chr1:11278872-11503002',
 'chr1:11503002-11724328',
 'chr1:11724328-11955069',
 'chr1:11955069-12186818',
 'chr1:12186818-12410804',
 'chr1:12410804-13677584',
 'chr1:13677584-13893991',
 'chr1:13893991-14110195',
 'chr1:14110195-14324312',
 'chr1:14324312-14547843',
 'chr1:14547843-14759654',
 'chr1:14759654-14977412',
 'chr1:14977412-15195891',
 'chr1:15195891-15416704',
 'chr1:15416704-15656764',
 'chr1:15656764-15902405',
 'chr1:15902405-16134290',
 'chr1:16134290-17108710',
 'chr1:17108710-17326678',
 'chr1:17326678-17567445',
 'chr1:17567445-17777104',
 'chr1:17777104-17987772',
 'chr1:17987772-18196383',
 'chr1:18196383-18401979',
 'chr1:18401979-18615870',
 'chr1:18615870-18826589',
 'chr1:18826589-19038400',
 'chr1:19038400-19251485',
 'chr1:19251485-19472583',
 'chr1:19472583-19706853',
 'chr1:19706853-19930662',
 'chr1:19930662-20161787',
 'chr1:20161787-20371770',
 'chr1:20371770-20590678',
 'chr1:20590678-20821750',
 'chr1:20821750-21043441',
 'chr1:21043441-21279115',
 'chr1:21279115-21542297',
 'chr1:21542297-21761190',
 'chr1:21761190-22018947',
 'chr1:22018947-22242704',
 'chr1:22242704-22456764',
 'chr1:22456764-22664837',
 'chr1:22664837-22875867',
 'chr1:22875867-23100476',
 'chr1:23100476-23331671',
 'chr1:23331671-23563511',
 'chr1:23563511-24139449',
 'chr1:24139449-24360876',
 'chr1:24360876-24581408',
 'chr1:24581408-24823636',
 'chr1:24823636-25035862',
 'chr1:25035862-25259676',
 'chr1:25259676-25575144',
 'chr1:25575144-25795406',
 'chr1:25795406-26022169',
 'chr1:26022169-26253199',
 'chr1:26253199-26487988',
 'chr1:26487988-26734811',
 'chr1:26734811-26975362',
 'chr1:26975362-27223176',
 'chr1:27223176-27458708',
 'chr1:27458708-27685740',
 'chr1:27685740-27931241',
 'chr1:27931241-28164534',
 'chr1:28164534-28418192',
 'chr1:28418192-28679501',
 'chr1:28679501-28925487',
 'chr1:28925487-29163140',
 'chr1:29163140-29600315',
 'chr1:29600315-29813280',
 'chr1:29813280-30023008',
 'chr1:30023008-30235406',
 'chr1:30235406-30451610',
 'chr1:30451610-30676655',
 'chr1:30676655-30887081',
 'chr1:30887081-31118594',
 'chr1:31118594-31359043',
 'chr1:31359043-31595970',
 'chr1:31595970-31801626',
 'chr1:31801626-32040848',
 'chr1:32040848-32281742',
 'chr1:32281742-32526110',
 'chr1:32526110-32777638',
 'chr1:32777638-33009750',
 'chr1:33009750-33240353',
 'chr1:33240353-33455194',
 'chr1:33455194-33664970',
 'chr1:33664970-33881591',
 'chr1:33881591-34091717',
 'chr1:34091717-34310709',
 'chr1:34310709-34516841',
 'chr1:34516841-34736442',
 'chr1:34736442-34947162',
 'chr1:34947162-35200758',
 'chr1:35200758-35433225',
 'chr1:35433225-35654347',
 'chr1:35654347-35889544',
 'chr1:35889544-36117159',
 'chr1:36117159-36354687',
 'chr1:36354687-36580421',
 'chr1:36580421-36790608',
 'chr1:36790608-36995301',
 'chr1:36995301-37203127',
 'chr1:37203127-37424389',
 'chr1:37424389-37651091',
 'chr1:37651091-37873972',
 'chr1:37873972-38111845',
 'chr1:38111845-38322779',
 'chr1:38322779-38538570',
 'chr1:38538570-38753985',
 'chr1:38753985-38995620',
 'chr1:38995620-39238287',
 'chr1:39238287-39461330',
 'chr1:39461330-39702264',
 'chr1:39702264-39946814',
 'chr1:39946814-40183121',
 'chr1:40183121-40415842',
 'chr1:40415842-40651928',
 'chr1:40651928-40868291',
 'chr1:40868291-41096298',
 'chr1:41096298-41320987',
 'chr1:41320987-41525935',
 'chr1:41525935-41735464',
 'chr1:41735464-41943586',
 'chr1:41943586-42168808',
 'chr1:42168808-42390589',
 'chr1:42390589-42613844',
 'chr1:42613844-42841006',
 'chr1:42841006-43066488',
 'chr1:43066488-43300000',
 'chr1:43300000-43520730',
 'chr1:43520730-43740019',
 'chr1:43740019-43956420',
 'chr1:43956420-44177542',
 'chr1:44177542-44389254',
 'chr1:44389254-44607748',
 'chr1:44607748-44839537',
 'chr1:44839537-45078807',
 'chr1:45078807-45330532',
 'chr1:45330532-45575545',
 'chr1:45575545-45819446',
 'chr1:45819446-46046996',
 'chr1:46046996-46279045',
 'chr1:46279045-46514026',
 'chr1:46514026-46730051',
 'chr1:46730051-47027817',
 'chr1:47027817-47303866',
 'chr1:47303866-47528543',
 'chr1:47528543-47737794',
 'chr1:47737794-47940906',
 'chr1:47940906-48163917',
 'chr1:48163917-48401104',
 'chr1:48401104-48623398',
 'chr1:48623398-48828244',
 'chr1:48828244-49040375',
 'chr1:49040375-49268353',
 'chr1:49268353-49489357',
 'chr1:49489357-49725897',
 'chr1:49725897-49969755',
 'chr1:49969755-50181051',
 'chr1:50181051-50397325',
 'chr1:50397325-50612598',
 'chr1:50612598-50843866',
 'chr1:50843866-51080082',
 'chr1:51080082-51311650',
 'chr1:51311650-51541689',
 'chr1:51541689-51764720',
 'chr1:51764720-51985487',
 'chr1:51985487-52232407',
 'chr1:52232407-52462041',
 'chr1:52462041-52688455',
 'chr1:52688455-52932444',
 'chr1:52932444-53155506',
 'chr1:53155506-53368072',
 'chr1:53368072-53581561',
 'chr1:53581561-53790970',
 'chr1:53790970-54020097',
 'chr1:54020097-54240519',
 'chr1:54240519-54463118',
 'chr1:54463118-54698091',
 'chr1:54698091-54923212',
 'chr1:54923212-55142657',
 'chr1:55142657-55358117',
 'chr1:55358117-55580534',
 'chr1:55580534-55796192',
 'chr1:55796192-56004831',
 'chr1:56004831-56218770',
 'chr1:56218770-56437336',
 'chr1:56437336-56655780',
 'chr1:56655780-56866589',
 'chr1:56866589-57072999',
 'chr1:57072999-57280809',
 'chr1:57280809-57490206',
 'chr1:57490206-57709142',
 'chr1:57709142-57917694',
 'chr1:57917694-58133311',
 'chr1:58133311-58354593',
 'chr1:58354593-58574467',
 'chr1:58574467-58793135',
 'chr1:58793135-59005597',
 'chr1:59005597-59215264',
 'chr1:59215264-59435338',
 'chr1:59435338-59674085',
 'chr1:59674085-59885673',
 'chr1:59885673-60095453',
 'chr1:60095453-60311261',
 'chr1:60311261-60538303',
 'chr1:60538303-60756451',
 'chr1:60756451-60974834',
 'chr1:60974834-61186752',
 'chr1:61186752-61396331',
 'chr1:61396331-61611136',
 'chr1:61611136-61841171',
 'chr1:61841171-62070508',
 'chr1:62070508-62307099',
 'chr1:62307099-62530811',
 'chr1:62530811-62766850',
 'chr1:62766850-62981638',
 'chr1:62981638-63191464',
 'chr1:63191464-63419702',
 'chr1:63419702-63642491',
 'chr1:63642491-63854704',
 'chr1:63854704-64061613',
 'chr1:64061613-64284698',
 'chr1:64284698-64506779',
 'chr1:64506779-64717115',
 'chr1:64717115-64931806',
 'chr1:64931806-65160400',
 'chr1:65160400-65377507',
 'chr1:65377507-65609504',
 'chr1:65609504-65834471',
 'chr1:65834471-66055681',
 'chr1:66055681-66279180',
 'chr1:66279180-66498175',
 'chr1:66498175-66707630',
 'chr1:66707630-66929181',
 'chr1:66929181-67147896',
 'chr1:67147896-67382537',
 'chr1:67382537-67610312',
 'chr1:67610312-67820292',
 'chr1:67820292-68036238',
 'chr1:68036238-68251073',
 'chr1:68251073-68472249',
 'chr1:68472249-68690571',
 'chr1:68690571-68918068',
 'chr1:68918068-69151238',
 'chr1:69151238-69362763',
 'chr1:69362763-69583523',
 'chr1:69583523-69789698',
 'chr1:69789698-70023608',
 'chr1:70023608-70234175',
 'chr1:70234175-70462518',
 'chr1:70462518-70688373',
 'chr1:70688373-70908277',
 'chr1:70908277-71122334',
 'chr1:71122334-71343476',
 'chr1:71343476-71557048',
 'chr1:71557048-71764822',
 'chr1:71764822-71980283',
 'chr1:71980283-72186128',
 'chr1:72186128-72400637',
 'chr1:72400637-72611276',
 'chr1:72611276-72820388',
 'chr1:72820388-73045332',
 'chr1:73045332-73261354',
 'chr1:73261354-73475764',
 'chr1:73475764-73688879',
 'chr1:73688879-73896442',
 'chr1:73896442-74113116',
 'chr1:74113116-74326852',
 'chr1:74326852-74545358',
 'chr1:74545358-74755814',
 'chr1:74755814-74982179',
 'chr1:74982179-75207662',
 'chr1:75207662-75434142',
 'chr1:75434142-75655103',
 'chr1:75655103-75902873',
 'chr1:75902873-76117451',
 'chr1:76117451-76329148',
 'chr1:76329148-76545258',
 'chr1:76545258-76755553',
 'chr1:76755553-76976166',
 'chr1:76976166-77200329',
 'chr1:77200329-77412631',
 'chr1:77412631-77627527',
 'chr1:77627527-77857880',
 'chr1:77857880-78085607',
 'chr1:78085607-78324280',
 'chr1:78324280-78539295',
 'chr1:78539295-78753021',
 'chr1:78753021-78972719',
 'chr1:78972719-79185514',
 'chr1:79185514-79396068',
 'chr1:79396068-79618444',
 'chr1:79618444-79835041',
 'chr1:79835041-80060761',
 'chr1:80060761-80276299',
 'chr1:80276299-80496602',
 'chr1:80496602-80710944',
 'chr1:80710944-80922134',
 'chr1:80922134-81140456',
 'chr1:81140456-81352426',
 'chr1:81352426-81563831',
 'chr1:81563831-81782033',
 'chr1:81782033-81989256',
 'chr1:81989256-82207676',
 'chr1:82207676-82424272',
 'chr1:82424272-82633965',
 'chr1:82633965-82840724',
 'chr1:82840724-83497455',
 'chr1:83497455-83709641',
 'chr1:83709641-83918435',
 'chr1:83918435-84133979',
 'chr1:84133979-84347979',
 'chr1:84347979-84564540',
 'chr1:84564540-84776670',
 'chr1:84776670-84990785',
 'chr1:84990785-85209426',
 'chr1:85209426-85423257',
 'chr1:85423257-85640098',
 'chr1:85640098-85881026',
 'chr1:85881026-86105707',
 'chr1:86105707-86330996',
 'chr1:86330996-86549916',
 'chr1:86549916-86785880',
 'chr1:86785880-87020136',
 'chr1:87020136-87227189',
 'chr1:87227189-87442092',
 'chr1:87442092-87662189',
 'chr1:87662189-87870078',
 'chr1:87870078-88075229',
 'chr1:88075229-88284944',
 'chr1:88284944-88497189',
 'chr1:88497189-88711016',
 'chr1:88711016-88941106',
 'chr1:88941106-89176544',
 'chr1:89176544-89411495',
 'chr1:89411495-89640959',
 'chr1:89640959-89862637',
 'chr1:89862637-90083999',
 'chr1:90083999-90312540',
 'chr1:90312540-90522150',
 'chr1:90522150-90736781',
 'chr1:90736781-90952738',
 'chr1:90952738-91185166',
 'chr1:91185166-91438398',
 'chr1:91438398-91659746',
 'chr1:91659746-91877195',
 'chr1:91877195-92110011',
 'chr1:92110011-92342145',
 'chr1:92342145-92582895',
 'chr1:92582895-92824003',
 'chr1:92824003-93051176',
 'chr1:93051176-93273930',
 'chr1:93273930-93503510',
 'chr1:93503510-93721891',
 'chr1:93721891-93959195',
 'chr1:93959195-94173877',
 'chr1:94173877-94395435',
 'chr1:94395435-94619865',
 'chr1:94619865-94835732',
 'chr1:94835732-95051291',
 'chr1:95051291-95277904',
 'chr1:95277904-95494962',
 'chr1:95494962-95703585',
 'chr1:95703585-95915690',
 'chr1:95915690-96130330',
 'chr1:96130330-96353952',
 'chr1:96353952-96575849',
 'chr1:96575849-96805114',
 'chr1:96805114-97020061',
 'chr1:97020061-97228919',
 'chr1:97228919-97452591',
 'chr1:97452591-97663949',
 'chr1:97663949-97870488',
 'chr1:97870488-98074839',
 'chr1:98074839-98290020',
 'chr1:98290020-98497589',
 'chr1:98497589-98720135',
 'chr1:98720135-98936487',
 'chr1:98936487-99152441',
 'chr1:99152441-99371885',
 'chr1:99371885-99598181',
 'chr1:99598181-99814521',
 'chr1:99814521-100038888',
 'chr1:100038888-100263048',
 'chr1:100263048-100479752',
 'chr1:100479752-100710884',
 'chr1:100710884-100930007',
 'chr1:100930007-101145683',
 'chr1:101145683-101363050',
 'chr1:101363050-101577456',
 'chr1:101577456-101793614',
 'chr1:101793614-102000957',
 'chr1:102000957-102214987',
 'chr1:102214987-102432771',
 'chr1:102432771-102659015',
 'chr1:102659015-102883863',
 'chr1:102883863-103829338',
 'chr1:103829338-104047741',
 'chr1:104047741-104265349',
 'chr1:104265349-104485605',
 'chr1:104485605-104709789',
 'chr1:104709789-104942575',
 'chr1:104942575-105153238',
 'chr1:105153238-105375765',
 'chr1:105375765-105588691',
 'chr1:105588691-105803452',
 'chr1:105803452-106025160',
 'chr1:106025160-106240899',
 'chr1:106240899-106459323',
 'chr1:106459323-106675204',
 'chr1:106675204-106885026',
 'chr1:106885026-107100107',
 'chr1:107100107-107307938',
 'chr1:107307938-107512829',
 'chr1:107512829-107728221',
 'chr1:107728221-107942131',
 'chr1:107942131-108601511',
 'chr1:108601511-108819473',
 'chr1:108819473-109049087',
 'chr1:109049087-109280696',
 'chr1:109280696-109500052',
 'chr1:109500052-109738678',
 'chr1:109738678-109964685',
 'chr1:109964685-110172002',
 'chr1:110172002-110383382',
 'chr1:110383382-110594702',
 'chr1:110594702-110802908',
 'chr1:110802908-111026818',
 'chr1:111026818-111251378',
 'chr1:111251378-111476812',
 'chr1:111476812-111697035',
 'chr1:111697035-111902720',
 'chr1:111902720-112106813',
 'chr1:112106813-112343438',
 'chr1:112343438-112564006',
 'chr1:112564006-112796771',
 'chr1:112796771-113055562',
 'chr1:113055562-113284097',
 'chr1:113284097-113520679',
 'chr1:113520679-113752166',
 'chr1:113752166-113972000',
 'chr1:113972000-114188923',
 'chr1:114188923-114412694',
 'chr1:114412694-114636864',
 'chr1:114636864-114858966',
 'chr1:114858966-115087797',
 'chr1:115087797-115298237',
 'chr1:115298237-115511499',
 'chr1:115511499-115734313',
 'chr1:115734313-115947627',
 'chr1:115947627-116171919',
 'chr1:116171919-116382224',
 'chr1:116382224-116593361',
 'chr1:116593361-116845842',
 'chr1:116845842-117064605',
 'chr1:117064605-117286850',
 'chr1:117286850-117512220',
 'chr1:117512220-117728296',
 'chr1:117728296-117945245',
 'chr1:117945245-118156882',
 'chr1:118156882-118377918',
 'chr1:118377918-118607043',
 'chr1:118607043-118842234',
 'chr1:118842234-119061090',
 'chr1:119061090-119290318',
 'chr1:119290318-119512633',
 'chr1:119512633-119749033',
 'chr1:119749033-145914487',
 'chr1:145914487-147248042',
 'chr1:147248042-147495119',
 'chr1:147495119-149912326',
 'chr1:149912326-150144266',
 'chr1:150144266-150387993',
 'chr1:150387993-150636358',
 'chr1:150636358-150879075',
 'chr1:150879075-151128105',
 'chr1:151128105-151368789',
 'chr1:151368789-151602464',
 'chr1:151602464-151825986',
 'chr1:151825986-152046119',
 'chr1:152046119-152280279',
 'chr1:152280279-152517159',
 'chr1:152517159-152739629',
 'chr1:152739629-152961365',
 'chr1:152961365-153187809',
 'chr1:153187809-153403713',
 'chr1:153403713-153641402',
 'chr1:153641402-153878377',
 'chr1:153878377-154134304',
 'chr1:154134304-154379780',
 'chr1:154379780-154607082',
 'chr1:154607082-154828346',
 'chr1:154828346-155048430',
 'chr1:155048430-155291599',
 'chr1:155291599-155532011',
 'chr1:155532011-155819060',
 'chr1:155819060-156064388',
 'chr1:156064388-156296652',
 'chr1:156296652-156524193',
 'chr1:156524193-156746257',
 'chr1:156746257-156962173',
 'chr1:156962173-157178251',
 'chr1:157178251-157417553',
 'chr1:157417553-157640868',
 'chr1:157640868-157856425',
 'chr1:157856425-158071726',
 'chr1:158071726-158311026',
 'chr1:158311026-158539792',
 'chr1:158539792-158750549',
 'chr1:158750549-158978332',
 'chr1:158978332-159198222',
 'chr1:159198222-159425163',
 'chr1:159425163-159660745',
 'chr1:159660745-159880829',
 'chr1:159880829-160089925',
 'chr1:160089925-160303931',
 'chr1:160303931-160532797',
 'chr1:160532797-160758712',
 'chr1:160758712-161001271',
 'chr1:161001271-161233148',
 'chr1:161233148-161845315',
 'chr1:161845315-162053934',
 'chr1:162053934-162265880',
 'chr1:162265880-162491307',
 'chr1:162491307-162709345',
 'chr1:162709345-162950154',
 'chr1:162950154-163163403',
 'chr1:163163403-163376515',
 'chr1:163376515-163586858',
 'chr1:163586858-163809284',
 'chr1:163809284-164028040',
 'chr1:164028040-164254747',
 'chr1:164254747-164473606',
 'chr1:164473606-164690252',
 'chr1:164690252-164895973',
 'chr1:164895973-165119714',
 'chr1:165119714-165325820',
 'chr1:165325820-165532033',
 'chr1:165532033-165752115',
 'chr1:165752115-165984515',
 'chr1:165984515-166198816',
 'chr1:166198816-166448876',
 'chr1:166448876-166673466',
 'chr1:166673466-166898377',
 'chr1:166898377-167106276',
 'chr1:167106276-167319495',
 'chr1:167319495-167534027',
 'chr1:167534027-167753922',
 'chr1:167753922-167980446',
 'chr1:167980446-168198476',
 'chr1:168198476-168421646',
 'chr1:168421646-168643984',
 'chr1:168643984-168861603',
 'chr1:168861603-169080284',
 'chr1:169080284-169304699',
 'chr1:169304699-169528654',
 'chr1:169528654-169751154',
 'chr1:169751154-169965421',
 'chr1:169965421-170197248',
 'chr1:170197248-170412066',
 'chr1:170412066-170643795',
 'chr1:170643795-170861709',
 'chr1:170861709-171082238',
 'chr1:171082238-171299706',
 'chr1:171299706-171536496',
 'chr1:171536496-171770645',
 'chr1:171770645-171982090',
 'chr1:171982090-172207656',
 'chr1:172207656-172427250',
 'chr1:172427250-172644528',
 'chr1:172644528-172860908',
 'chr1:172860908-173089314',
 'chr1:173089314-173312529',
 'chr1:173312529-173546052',
 'chr1:173546052-173789072',
 'chr1:173789072-174022275',
 'chr1:174022275-174263169',
 'chr1:174263169-174489958',
 'chr1:174489958-174739915',
 'chr1:174739915-174971777',
 'chr1:174971777-175189868',
 'chr1:175189868-175406482',
 'chr1:175406482-175616249',
 'chr1:175616249-175822326',
 'chr1:175822326-176044571',
 'chr1:176044571-176270268',
 'chr1:176270268-176499357',
 'chr1:176499357-176709005',
 'chr1:176709005-176917313',
 'chr1:176917313-177121286',
 'chr1:177121286-177331776',
 'chr1:177331776-177548248',
 'chr1:177548248-177780430',
 'chr1:177780430-177996340',
 'chr1:177996340-178217487',
 'chr1:178217487-178440372',
 'chr1:178440372-178658475',
 'chr1:178658475-178885137',
 'chr1:178885137-179114318',
 'chr1:179114318-179348287',
 'chr1:179348287-179594811',
 'chr1:179594811-179820736',
 'chr1:179820736-180042692',
 'chr1:180042692-180255425',
 'chr1:180255425-180482121',
 'chr1:180482121-180704459',
 'chr1:180704459-180930033',
 'chr1:180930033-181150199',
 'chr1:181150199-181377542',
 'chr1:181377542-181583400',
 'chr1:181583400-181789594',
 'chr1:181789594-182022011',
 'chr1:182022011-182238525',
 'chr1:182238525-182460479',
 'chr1:182460479-182675093',
 'chr1:182675093-182889723',
 'chr1:182889723-183115329',
 'chr1:183115329-183332586',
 'chr1:183332586-183550220',
 'chr1:183550220-183783343',
 'chr1:183783343-183990622',
 'chr1:183990622-184205795',
 'chr1:184205795-184426303',
 'chr1:184426303-184637897',
 'chr1:184637897-184859950',
 'chr1:184859950-185081746',
 'chr1:185081746-185308532',
 'chr1:185308532-185527486',
 'chr1:185527486-185753227',
 'chr1:185753227-185974266',
 'chr1:185974266-186186049',
 'chr1:186186049-186405232',
 'chr1:186405232-186625455',
 'chr1:186625455-186849159',
 'chr1:186849159-187061127',
 'chr1:187061127-187276293',
 'chr1:187276293-187493589',
 'chr1:187493589-187715573',
 'chr1:187715573-187939956',
 'chr1:187939956-188151148',
 'chr1:188151148-188363046',
 'chr1:188363046-188572350',
 'chr1:188572350-188789265',
 'chr1:188789265-189005075',
 'chr1:189005075-189222446',
 'chr1:189222446-189445618',
 'chr1:189445618-189660925',
 'chr1:189660925-189876427',
 'chr1:189876427-190085879',
 'chr1:190085879-190293543',
 'chr1:190293543-190501047',
 'chr1:190501047-190711137',
 'chr1:190711137-190923897',
 'chr1:190923897-191143319',
 'chr1:191143319-191354958',
 'chr1:191354958-191572387',
 'chr1:191572387-191782725',
 'chr1:191782725-191995335',
 'chr1:191995335-192207568',
 'chr1:192207568-192418332',
 'chr1:192418332-192641127',
 'chr1:192641127-192864746',
 'chr1:192864746-193079928',
 'chr1:193079928-193294087',
 'chr1:193294087-193508024',
 'chr1:193508024-193727313',
 'chr1:193727313-193944781',
 'chr1:193944781-194162690',
 'chr1:194162690-194379752',
 'chr1:194379752-194596307',
 'chr1:194596307-194810588',
 'chr1:194810588-195022375',
 'chr1:195022375-195239918',
 'chr1:195239918-195448469',

The above `genomic_regions` is a `List` that define the binning interval for the reference. The same binning should be passed to the `SpaceNumbat` pipeline.

## Load reference dataset

We use the dataset [GSE184462](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE184462), that contains various samples collected from different tissues of multiple donors. We specifically use the supplementary file used in the linked GEO records.

First, we load and process the metadata:

In [12]:
atlas_samples_dir = "/beegfs/scratch/ric.cosr/ric.cosr/InnovationLab/spatial_dataset/spatial_multiomics/atac_reference_building/GSE184462_RAW"
atlas_metadata_path = "/beegfs/scratch/ric.cosr/ric.cosr/InnovationLab/spatial_dataset/spatial_multiomics/atac_reference_building/GSE184462_metadata.tsv"

In [13]:
metadata_atlas = pd.read_table(atlas_metadata_path)
metadata_atlas.columns = [str.lower("_".join(i.split(" "))) for i in metadata_atlas.columns]
metadata_atlas["barcode"] = [i.split("+")[1] for i in metadata_atlas.cellid]

We then extract the list of the genomic bin we calculated before and load the data for which metadata are available.

In [14]:
import os
import tqdm
from spacenumbat.preprocessing.multiome_unpaired import get_atac_binning
from spacenumbat.preprocessing.build_atac_ref import build_atac_reference
import anndata as ad

In [ ]:
atlas_dict = {}

for frag_file in tqdm.tqdm(os.listdir(atlas_samples_dir)):
    full_frag_path = os.path.join(atlas_samples_dir, frag_file)
    frag_file_split = frag_file.split("_")
    gsm_name = frag_file_split[0]
    sample_name = "_".join(frag_file_split[1:-2])
    current_sample_df = metadata_atlas[metadata_atlas["tissue"] == sample_name].loc[:,['sample', 
                                                                                       'tissue',
                                                                                       'cell_type', 
                                                                                       'life_stage',
                                                                                       'barcode']]
    if current_sample_df.shape[0] > 0:
    
        current_barcodes = current_sample_df["barcode"].tolist()
    
        atlas_dict[sample_name] = get_atac_binning(fragments_path=full_frag_path, 
                                                   genomic_regions=genomic_regions,
                                                   barcodes=current_barcodes,
                                                   counting_strategy="fragment",
                                                   min_num_fragments=0)

In [ ]:
for current_key, current_adata in atlas_dict.items():

    current_adata.obs = pd.merge(atlas_dict[current_key].obs, 
                                 metadata_atlas[metadata_atlas["tissue"] == current_key].loc[:,['sample', 
                                                                                                'tissue',
                                                                                                'cell_type', 
                                                                                                'life_stage',
                                                                                                'barcode']],
                                 left_index=True,
                                 right_on="barcode").set_index("barcode", drop=False)

for current_key, current_adata in atlas_dict.items():
    current_adata.obs["cellid"] = current_adata.obs["tissue"] + "_" + current_adata.obs["barcode"]
    current_adata.obs = current_adata.obs.set_index("cellid", drop=True)

In [ ]:
full_ad = ad.concat(atlas_dict, join="outer")

In [ ]:
full_ad.obs[["tissue_ref", "donor"]] = full_ad.obs["tissue"].str.rsplit("_", n=1, expand=True)

In [ ]:
atlas_adata_path = "/beegfs/scratch/ric.cosr/ric.cosr/InnovationLab/spatial_dataset/spatial_multiomics/atac_reference_building/atlas_adata.h5ad"
full_ad.write_h5ad(atlas_adata_path)

Our anndata at this point is as follow:

In [16]:
full_ad = ad.read_h5ad(atlas_adata_path)

In [17]:
full_ad

AnnData object with n_obs × n_vars = 484608 × 12145
    obs: 'n_fragment', 'frac_dup', 'frac_mito', 'sample', 'tissue', 'cell_type', 'life_stage', 'barcode', 'tissue_ref', 'donor'

In [18]:
full_ad.obs.head()

,n_fragment,frac_dup,frac_mito,sample,tissue,cell_type,life_stage,barcode,tissue_ref,donor
cellid,,,,,,,,,,
artery_aorta_SM-JF1NU_AAACGCAAGCAAAGCCCACGAC,5074,0.389020,0.021597,artery_aorta_SM-JF1NU_1,artery_aorta_SM-JF1NU,Vascular Smooth Muscle 1,Adult,AAACGCAAGCAAAGCCCACGAC,artery_aorta,SM-JF1NU
artery_aorta_SM-JF1NU_AAACGCAAGCAAAGCGGGAGCT,6583,0.384553,0.033759,artery_aorta_SM-JF1NU_1,artery_aorta_SM-JF1NU,Vascular Smooth Muscle 1,Adult,AAACGCAAGCAAAGCGGGAGCT,artery_aorta,SM-JF1NU
artery_aorta_SM-JF1NU_AAACGCAAGCAAAGGAACAGAC,4502,0.388786,0.094347,artery_aorta_SM-JF1NU_1,artery_aorta_SM-JF1NU,Fibroblast (General),Adult,AAACGCAAGCAAAGGAACAGAC,artery_aorta,SM-JF1NU
artery_aorta_SM-JF1NU_AAACGCAAGCAAAGGGATGCCA,6101,0.400706,0.001146,artery_aorta_SM-JF1NU_1,artery_aorta_SM-JF1NU,"Macrophage (General,Alveolar)",Adult,AAACGCAAGCAAAGGGATGCCA,artery_aorta,SM-JF1NU
artery_aorta_SM-JF1NU_AAACGCAAGCAACCATGCATGA,2382,0.386880,0.099433,artery_aorta_SM-JF1NU_1,artery_aorta_SM-JF1NU,T Lymphocyte 1 (CD8+),Adult,AAACGCAAGCAACCATGCATGA,artery_aorta,SM-JF1NU

In [19]:
full_ad.var.head()

Empty DataFrame
Columns: []
Index: [chr1:0-1042457, chr1:1042457-1265484, chr1:1265484-1519859, chr1:1519859-1826619, chr1:1826619-2058465]

In [20]:
(atac_reference,
 atac_manifest,
 atac_bin_gtf,
 atac_diag) = build_atac_reference(full_ad,
                                   donor_col='donor',
                                   tissue_col='tissue_ref',
                                   cell_type_col='cell_type',
                                   life_stage_col='life_stage',
                                   life_stage='Adult',
                                   min_cells=50,
                                   min_fragments=50_000,
                                   min_donors=1,
                                   min_tissue_donors=2,
                                   subtype_ratio_threshold=1.5,
                                   tissue_ratio_threshold=2.0,
                                   return_diagnostics=True)

In [22]:
atac_reference.columns = [str.lower("_".join(i.split(" "))) for i in atac_reference.columns]

In [23]:
atac_reference.head()

,adipocyte,airway_goblet_cell,alveolar_capillary_endothelial_cell,alveolar_type_1_(at1)_cell,alveolar_type_2_(at2)_cell,atrial_cardiomyocyte,basal_epidermal_(skin),basal_epithelial_(mammary),cd4_t,cd8_t,...,thyroid_follicular_cell,transitional_zone_cortical_cell,tuft_cell,type_i_skeletal_myocyte,type_ii_skeletal_myocyte,vascular_smooth_muscle_1,vascular_smooth_muscle_2,ventricular_cardiomyocyte,zona_fasciculata_cortical_cell,zona_glomerulosa_cortical_cell
chr1:0-1042457,0.000252,0.000303,0.000260,0.000239,0.000287,0.000303,0.000412,0.000543,0.000604,0.000342,...,0.000262,0.000655,0.000747,0.000377,0.000387,0.000396,0.000520,0.000335,0.000543,0.000573
chr1:1042457-1265484,0.000163,0.000513,0.000151,0.000161,0.000166,0.000109,0.000321,0.000431,0.000348,0.000250,...,0.000149,0.000172,0.000483,0.000121,0.000117,0.000147,0.000120,0.000111,0.000165,0.000167
chr1:1265484-1519859,0.000371,0.000483,0.000186,0.000248,0.000243,0.000168,0.000477,0.000584,0.000351,0.000281,...,0.000231,0.000528,0.000419,0.000412,0.000393,0.000326,0.000304,0.000241,0.000513,0.000500
chr1:1519859-1826619,0.000365,0.000281,0.000180,0.000141,0.000159,0.000143,0.000380,0.000349,0.000285,0.000270,...,0.000241,0.000500,0.000229,0.000286,0.000283,0.000249,0.000172,0.000191,0.000586,0.000450
chr1:1826619-2058465,0.000196,0.000201,0.000136,0.000156,0.000139,0.000145,0.000254,0.000244,0.000259,0.000182,...,0.000157,0.000369,0.000196,0.000174,0.000183,0.000144,0.000097,0.000184,0.000418,0.000337